name: Hourly Update abuse.ch Domains

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download fresh abuse.ch hostfile
        run: |
          curl -sSf https://urlhaus.abuse.ch/downloads/hostfile/ \
            -o fresh.txt

      - name: Extract just domains (no comments/blanks), sort
        run: |
          grep -Ev '^#|^$' fresh.txt | sort -u > scraped.txt

      - name: Prepare existing list
        run: |
          # ensure the file exists
          touch domains.txt
          # extract & sort your current domains
          grep -Ev '^#|^$' domains.txt | sort -u > existing.txt

      - name: Find truly new domains
        run: |
          comm -23 scraped.txt existing.txt > new.txt

      - name: Append new domains (if any) and commit
        run: |
          if [ -s new.txt ]; then
            cat new.txt >> domains.txt
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add domains.txt
            git commit -m "chore: add $(wc -l < new.txt) new domains"
            git push
          else
            echo "No new domains to add"
          fi
